version: '3.8'

services:
  jekyll-host:
    image: container.ldtteam.com/parchmentmc/smithingtable:latest
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 2
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.system==production
          - node.labels.type==worker
          - node.labels.web==true
      labels:
        - traefik.enable=true
        - traefik.constraint-label=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.routers.versioning-parchmentmc-org-http.rule=Host(`versioning.parchmentmc.org`)
        - traefik.http.routers.versioning-parchmentmc-org-http.entrypoints=http
        - traefik.http.routers.versioning-parchmentmc-org-http.middlewares=https-redirect
        - traefik.http.routers.versioning-parchmentmc-org-https.rule=Host(`versioning.parchmentmc.org`)
        - traefik.http.routers.versioning-parchmentmc-org-https.entrypoints=https
        - traefik.http.routers.versioning-parchmentmc-org-https.tls=true
        - traefik.http.routers.versioning-parchmentmc-org-https.service=versioning-parchmentmc-org
        - traefik.http.routers.versioning-parchmentmc-org-https.tls.certresolver=le
        - traefik.http.services.versioning-parchmentmc-org.loadbalancer.server.port=80
        - traefik.http.services.versioning-parchmentmc-org.loadBalancer.sticky.cookie.name=parchment-versioning
        - traefik.http.services.versioning-parchmentmc-org.loadBalancer.sticky.cookie.secure=true
        - traefik.http.services.versioning-parchmentmc-org.loadBalancer.sticky.cookie.httpOnly=true
        - traefik.http.services.versioning-parchmentmc-org.loadBalancer.sticky.cookie.sameSite=none
        - traefik.http.routers.versioning-parchmentmc-net-http.rule=Host(`versioning.parchmentmc.net`)
        - traefik.http.routers.versioning-parchmentmc-net-http.entrypoints=http
        - traefik.http.routers.versioning-parchmentmc-net-http.middlewares=https-redirect
        - traefik.http.routers.versioning-parchmentmc-net-https.rule=Host(`versioning.parchmentmc.net`)
        - traefik.http.routers.versioning-parchmentmc-net-https.entrypoints=https
        - traefik.http.routers.versioning-parchmentmc-net-https.tls=true
        - traefik.http.routers.versioning-parchmentmc-net-https.service=versioning-parchmentmc-net
        - traefik.http.routers.versioning-parchmentmc-net-https.tls.certresolver=le
        - traefik.http.services.versioning-parchmentmc-net.loadbalancer.server.port=80
        - traefik.http.services.versioning-parchmentmc-net.loadBalancer.sticky.cookie.name=parchment-versioning
        - traefik.http.services.versioning-parchmentmc-net.loadBalancer.sticky.cookie.secure=true
        - traefik.http.services.versioning-parchmentmc-net.loadBalancer.sticky.cookie.httpOnly=true
        - traefik.http.services.versioning-parchmentmc-net.loadBalancer.sticky.cookie.sameSite=none

networks:
  traefik-public:
    external: true
