replicaCount: 1

image:
  repository: ghcr.io/parchmentmc/smithingtable
  pullPolicy: IfNotPresent
  #tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-parchment
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/target: "cluster.ldtteam.com."
  hosts:
    - versioning.parchmentmc.org
    - versioning.parchmentmc.net
  tls: 
    - secretName: versioning-parchmentmc-tls
      hosts:
        - versioning.parchmentmc.org
        - versioning.parchmentmc.net

resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
  
topologySpreadConstraints:
  enabled: true
